import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkThemeProvider } from "./ClerkThemeProvider";
import { ThemeProvider } from "@/presentation/shared/ThemeProvider";
import { ApolloClientProvider } from "@/infrastructure/graphql/ApolloClientProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Orion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkThemeProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col">
          <ApolloClientProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ApolloClientProvider>
        </body>
      </html>
    </ClerkThemeProvider>
  );
}
