import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/presentation/shared/ThemeProvider";
import { ApolloClientProvider } from "@/infrastructure/graphql/ApolloClientProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorBackground: "#18181b",
          colorInputBackground: "#09090b",
          colorText: "#f4f4f5",
          colorTextSecondary: "#a1a1aa",
          colorPrimary: "#6366f1",
          colorInputText: "#f4f4f5",
          colorNeutral: "#e4e4e7",
        },
      }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col">
          <ApolloClientProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ApolloClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
