import type {
  AnalystSeedData,
  BoardColumn,
  BoardId,
} from "./types";
import { DEFAULT_COLUMN_DEFINITIONS } from "./types";

const COLUMN_PALETTE = ["#64748b", "#4f46e5", "#0ea5e9", "#f59e0b", "#ef4444", "#22c55e"];

const createColumnsForBoard = (boardId: BoardId): BoardColumn[] =>
  DEFAULT_COLUMN_DEFINITIONS.map((definition, index) => ({
    id: `${boardId}-${definition.name.toLowerCase().replace(/\s+/g, "-")}`,
    boardId,
    name: definition.name,
    states: definition.states,
    color: COLUMN_PALETTE[index] ?? "#64748b",
  }));

const engineeringColumns = createColumnsForBoard("board-engineering");
const productColumns = createColumnsForBoard("board-product");
const aiColumns = createColumnsForBoard("board-ai");

export const seedAnalystData: AnalystSeedData = {
  boards: [
    { id: "board-engineering", name: "Engineering Sprint", type: "scrum" },
    { id: "board-product", name: "Product Roadmap", type: "kanban" },
    { id: "board-ai", name: "AI Research Agents", type: "task" },
  ],
  boardColumns: [...engineeringColumns, ...productColumns, ...aiColumns],
  tickets: [
    {
      id: "epic-auth-hardening",
      ticketNumber: "OR-1",
      boardId: "board-engineering",
      columnId: "board-engineering-backlog",
      hierarchyType: "epic",
      parentTicketId: null,
      title: "Authentication Hardening Initiative",
      description: "Improve reliability and security across session lifecycle.",
      label: "security",
      fixVersion: "v1.2.0",
      storyPoints: 8,
      workflowState: "backlog",
      priority: "high",
      linkedTicketIds: ["story-auth-refresh"],
    },
    {
      id: "story-auth-refresh",
      ticketNumber: "OR-2",
      boardId: "board-engineering",
      columnId: "board-engineering-to-do",
      hierarchyType: "story",
      parentTicketId: "epic-auth-hardening",
      title: "Harden auth refresh flow",
      description: "Add replay protection and improve session timeout policy.",
      label: "backend",
      fixVersion: "v1.2.0",
      storyPoints: 5,
      workflowState: "todo",
      priority: "high",
      linkedTicketIds: ["epic-auth-hardening", "task-auth-rate-limit"],
    },
    {
      id: "story-roadmap-q3",
      ticketNumber: "OR-3",
      boardId: "board-product",
      columnId: "board-product-in-progress",
      hierarchyType: "story",
      parentTicketId: null,
      title: "Draft Q3 capacity split",
      description: "Map roadmap themes against cross-functional velocity.",
      label: "planning",
      fixVersion: "v1.1.0",
      storyPoints: 5,
      workflowState: "inProgress",
      priority: "medium",
      linkedTicketIds: ["epic-quarterly-planning"],
    },
    {
      id: "task-analyst-prompts",
      ticketNumber: "OR-4",
      boardId: "board-ai",
      columnId: "board-ai-to-do",
      hierarchyType: "task",
      parentTicketId: null,
      title: "Refine analyst prompt set",
      description: "Improve edge-case extraction for ambiguous requirements.",
      label: "ai",
      fixVersion: "v1.3.0",
      storyPoints: 3,
      workflowState: "todo",
      priority: "high",
      linkedTicketIds: ["story-ai-context-pipeline"],
    },
    {
      id: "task-auth-rate-limit",
      ticketNumber: "OR-5",
      boardId: "board-engineering",
      columnId: "board-engineering-in-progress",
      hierarchyType: "task",
      parentTicketId: "story-auth-refresh",
      title: "Implement token refresh rate limiting",
      description: "Prevent token burst abuse under high concurrency conditions.",
      label: "backend",
      fixVersion: "v1.2.0",
      storyPoints: 3,
      workflowState: "inProgress",
      priority: "high",
      linkedTicketIds: ["story-auth-refresh"],
    },
    {
      id: "task-auth-monitoring",
      ticketNumber: "OR-6",
      boardId: "board-engineering",
      columnId: "board-engineering-in-review",
      hierarchyType: "task",
      parentTicketId: "story-auth-refresh",
      title: "Add refresh anomaly dashboards",
      description: "Expose refresh failures and suspicious patterns in telemetry.",
      label: "observability",
      fixVersion: "v1.2.0",
      storyPoints: 2,
      workflowState: "inReview",
      priority: "medium",
      linkedTicketIds: [],
    },
    {
      id: "epic-quarterly-planning",
      ticketNumber: "OR-7",
      boardId: "board-product",
      columnId: "board-product-backlog",
      hierarchyType: "epic",
      parentTicketId: null,
      title: "Quarterly Planning Orchestration",
      description: "Align delivery pipeline and strategic initiatives for Q3.",
      label: "planning",
      fixVersion: "v1.1.0",
      storyPoints: 8,
      workflowState: "backlog",
      priority: "high",
      linkedTicketIds: ["story-roadmap-q3", "story-dependency-mapping"],
    },
    {
      id: "story-dependency-mapping",
      ticketNumber: "OR-8",
      boardId: "board-product",
      columnId: "board-product-to-do",
      hierarchyType: "story",
      parentTicketId: "epic-quarterly-planning",
      title: "Map cross-team dependencies",
      description: "Identify external blockers for major roadmap milestones.",
      label: "coordination",
      fixVersion: "v1.1.0",
      storyPoints: 5,
      workflowState: "todo",
      priority: "medium",
      linkedTicketIds: ["epic-quarterly-planning", "task-dependency-risk-matrix"],
    },
    {
      id: "task-dependency-risk-matrix",
      ticketNumber: "OR-9",
      boardId: "board-product",
      columnId: "board-product-in-qa",
      hierarchyType: "task",
      parentTicketId: "story-dependency-mapping",
      title: "Validate dependency risk matrix",
      description: "Review confidence and criticality scoring with stakeholders.",
      label: "analysis",
      fixVersion: "v1.1.0",
      storyPoints: 2,
      workflowState: "inQa",
      priority: "low",
      linkedTicketIds: ["story-dependency-mapping"],
    },
    {
      id: "story-ai-context-pipeline",
      ticketNumber: "OR-10",
      boardId: "board-ai",
      columnId: "board-ai-in-progress",
      hierarchyType: "story",
      parentTicketId: null,
      title: "Design AI context ingestion pipeline",
      description: "Define data contracts for requirement context handoff.",
      label: "ai",
      fixVersion: "v1.3.0",
      storyPoints: 8,
      workflowState: "inProgress",
      priority: "high",
      linkedTicketIds: ["task-analyst-prompts", "task-refinement-evals"],
    },
    {
      id: "task-refinement-evals",
      ticketNumber: "OR-11",
      boardId: "board-ai",
      columnId: "board-ai-in-review",
      hierarchyType: "task",
      parentTicketId: "story-ai-context-pipeline",
      title: "Create refinement quality eval set",
      description: "Score edge-case extraction quality against baseline prompts.",
      label: "mlops",
      fixVersion: "v1.3.0",
      storyPoints: 3,
      workflowState: "inReview",
      priority: "medium",
      linkedTicketIds: ["story-ai-context-pipeline"],
    },
    {
      id: "task-controller-alert-prompt",
      ticketNumber: "OR-12",
      boardId: "board-ai",
      columnId: "board-ai-ready",
      hierarchyType: "task",
      parentTicketId: "story-ai-context-pipeline",
      title: "Finalize controller alert template",
      description: "Standardize realistic de-scope recommendation output.",
      label: "ai",
      fixVersion: "v1.3.0",
      storyPoints: 1,
      workflowState: "ready",
      priority: "low",
      linkedTicketIds: [],
    },
  ],
};
